### ISSUE TITLE
Add font: Open Sans

### ISSUE THREAD

**Issue by pathmapper** [orangemug/font-glyphs#4]
Hi @orangemug,

would you mind adding _Open Sans Regular_ (and the other weights and italics) which are available e.g. here: https://github.com/google/fonts/tree/master/apache/opensans ?

The [glyph URL for the _Empty Style_ ](https://github.com/maputnik/editor/blob/b3a4628a793b672b7151944925f91418ad464b3b/src/config/empty-style.json#L11)in Maputnik is not working anymore and I would like to replace it with a free-to-use URL which has _Open Sans Regular_ available because the [`text-font`](https://www.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-text-font) property defaults to it.

Another option would be to use https://github.com/openmaptiles/fonts for this purpose, but I thought it's a good opportunity to make use of your repo here.

**Comment by orangemug** [comment]
@pathmapper that should now be added. Give it a try let me know if anything's incorrect.

**Comment by pathmapper** [comment]
Thanks a lot @orangemug, works great!

For better compability I've [submitted a PR](https://github.com/orangemug/font-glyphs/pull/5) to rename it to "Open Sans" which is used by Mapbox, Maptiler and OpenMapTiles for the glyphs.
